#!/bin/bash

# Set API endpoints and output files
POKEMON="pikachu"
URL="https://pokeapi.co/api/v2/pokemon/"
OUTPUT_FILE="data.json"
ERROR_FILE="errors.txt"

# Make the API request
curl -s -f "$URL" -o "$OUTPUT_FILE"

# Check if the curl command succeeded
if [ $? -ne 0 ]; then
    echo "Failed to fectch data"
else
    echo "Data fetched successfully and saved to $OUTPUT_FILE"
fi