#!/bin/bash

name="jq -r .name data.json"
height="jq -r .height data.json"
weight="jq -r .height data.json"
type="jq -r .types[0].type.name data.json"

# Make the API request
curl -s -f "$URL" -o "$OUTPUT_FILE"

# Check if the curl command succeeded
if [ $? -ne 0 ]; then
    echo "Failed to fectch data"
else
    echo "Data fetched successfully and saved to $OUTPUT_FILE"
fi