#!/bin/bash

# List for the names
POKEMONS=(bulbasaur ivysaur venusaur charmander charmeleon)
BASE_URL="https://pokeapi.co/api/v2/pokemon"
ERROR_LOG="errros.txt"
> "$ERROR_LOG" # this clears the previous errors

# Loop through the list
for name in "${POKEMONS[@]}"; do
    name_lower=$(echo "$name" | tr '[:upper:]' '[:lower:]')
    OUTPUT_FILE=${name_lower}.json
    ATTEMPT=1
    SUCCESS=0

    while [ $ATTEMPT -le 3 ]; do
        curl -s -f "$BASE_URL/$name_lower" -o "$OUTPUT_FILE"
        if [ $? -eq 0 ]; then
            echo "Success on attempt $ATTEMPT"
            SUCCESS=1
            break
        else
            echo "Attempt $ATTEMPT for $name failed."
            ((ATTEMPT++))
            sleep 2
        fi
    done

    if [ $SUCCESS -ne 1 ]; then
        echo "Failed to fetch $name after 3 attemps" >> "$ERROR_LOG"
    fi

    sleep 1
done