#!/bin/bash

# Setup API endpoints 
name=$(jq -r '.name' data.json | sed 's/.*/\u&/')
formatted_height=$(jq -r '.height' data.json | awk '{printf "%.1f", $1 / 10}')
formatted_weight=$(jq -r '.weight' data.json | awk '{printf "%.0f", $1 / 10}')
type=$(jq -r '.types[0].type.name' data.json | sed 's/.*/\u&/')


echo "$name is of type $type, weights ${weight}kg, and is ${height}m tall."